steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sodium-daylight-411413/first_app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sodium-daylight-411413/first_app']